### ISSUE TITLE
Ошибка "Invalid decoded address"

### ISSUE THREAD

**Issue by vol4tim** [positivecrash/robonomics-ui-vue#1]
При вводе текста, в тексовое поле `robo-address-polkadot`, получаю ошибку "Invalid decoded address".
Можешь добавить обработку таких исключений?
Ошибки нет, если корректный адрес вставлять целиком через буфер обмена.

![Screen](https://github.com/positivecrash/robonomics-ui-vue/assets/14287968/9e340920-33bf-432a-ac2e-e26cc8bf7aa5)

**Comment by positivecrash** [comment]
fixed
